# ansible-playbook deploy.yaml -i inventories/dev/hosts --vault-id ~/.tokens/vault.txt

- hosts: all
  strategy: free

  tasks:

    - name: "Ensuring existence of directory: {{ app_data }}/data"
      command: mkdir -p {{ app_data }}/data
      args:
        warn: no
      become: yes
      become_user: "{{ user }}"

    - name: Render docker-compose.yaml
      template:
        src: docker-compose.yaml.j2
        dest: '{{ app_data }}/docker-compose.yaml'

    - name: Run `docker stack deploy`
      shell: docker stack deploy -c {{ app_data }}/docker-compose.yaml {{ env }}_portainer
