# ansible-playbook deploy.yaml -i inventories/dev/hosts --vault-id ~/.tokens/master_id

- hosts: all
  strategy: free

  tasks:
    - name: Render docker-compose.yaml & deploy stack
      import_role:
        name: docker-deploy
      vars:
        with_registry: no
